language: php

php:
  - 5.6
  - 7.0
  - nightly
  
matrix:
    fast_finish: true
    allow_failures:
      - php: "7.0"

script:
  - mkdir ./tests/logs/
  - ./vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml

